export default [
  {
    truck_plate: '30A-50493',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50494',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50495',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50496',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50497',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50498',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50499',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50400',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50401',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50402',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50403',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50404',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50405',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50406',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50407',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50408',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50409',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50410',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50411',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50411',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50411',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50412',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50413',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50414',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50415',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50416',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50417',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50418',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50419',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50420',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50421',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
  {
    truck_plate: '30A-50422',
    cargo_type: 'Computer,Electronic',
    driver: 'Nguyen Van A',
    truck_type: '5 ton',
    price: '1000000000',
    dimension: '10-2-1.5',
    parking_address: 'No. 128, Hoàn Kiếm street, Hà Nội',
    production_year: '2010',
    status: 1,
    description: 'Thông tin của xe',
  },
];
